say_title ( mob_name ( 30130 ) ) 
say ( locale_quest ( 91722 ) ) 
local s = select ( locale_quest ( 811 ) , locale_quest ( 812 ) ) 
if s == 2 then 
return 
end 
local settings = akumea_dungeon_lv75_s3 . settings ( ) 
if dungeonLib . CheckEnter ( "akumea_dungeon_lv75_s3" , settings [ "cooldown" ] , settings [ "requirements" ] ) == false then 
return 
end 
say_reward ( locale_quest ( 91723 ) ) 
wait ( ) 
akumea_dungeon_lv75_s3 . create_dungeon ( ) 
