say_title ( mob_name ( DUNGEON_NPC ) ) 
say ( locale_quest ( 91722 ) ) 
local s = select ( locale_quest ( 811 ) , locale_quest ( 812 ) ) 
if s == 2 then 
return 
end 
local settings = akumea_dungeon_lv105_py . settings ( ) 
if dungeonLib . CheckEnter ( "akumea_dungeon_lv105_py" , settings [ "cooldown" ] , settings [ "requirements" ] ) == false then 
return 
end 
say_reward ( locale_quest ( 91728 ) ) 
wait ( ) 
akumea_dungeon_lv105_py . create_dungeon ( ) 
