version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: lyris-mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: iperi122
    ports:
      - "0.0.0.0:3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./migrate:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/my.cnf