version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: lyris-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "iperi122"]